name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: composer-php
        uses: nick-zh/composer@php7.4
      
      - name: run tests
        run: composer tests
